#%RAML 1.0
title: RetrieveTravelOnTipRoutesAndSchedule-SAPI
description: This API will fetch the Routes and schedules from Travel On Tip system
baseUri: https://localhost:8081/
protocols: [HTTP, HTTPS]
version: v1


types:
  400ResponseDataType: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesdatatypes/1.0.0/dataTypes/400ResponseDataType.raml
  404ResponseDataType: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesdatatypes/1.0.0/dataTypes/404ResponseDataType.raml
  500ResponseDataType: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesdatatypes/1.0.0/dataTypes/500ResponseDataType.raml

uses: 
  common: /library/commonBusinessLibrary.raml

securitySchemes:
  BA: !include /library/SecuritySchems/BAsecurityScheme.raml

securedBy:
  - BA

/{transportType}:
  /{transportCompany}:
    /routes:
      get:
        is:
          - common.transactionId
        responses:
          200:
            body:
              application/json:
                type: common.200ResponseForTravelOnTipRoutsDataTypes     
                example: !include /library/Routs/examples/200ResponseForTravelOnTipRouts.json          
          400:
            body:
              application/json:
                type: 400ResponseDataType
                example: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesexamples/1.0.0/examples/400Response-example.json
          404:
            body:
              application/json:
                type: 404ResponseDataType
                example: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesexamples/1.0.0/examples/404Response-example.json
          500:
            body:
              application/json:
                type: 500ResponseDataType
                example: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesexamples/1.0.0/examples/500Response-example.json
                  
    /schedules:
      get:
        is:
          - common.transactionId
          - common.departureLocationCode
          - common.destinationLocationCode
        responses:
          200:
            body:
              application/json:
                type: common.200ResponseForTravelOnTipScheduleDataType
                example: !include /library/schedules/examples/200ResponseForTravelOnTipSchdelesExample.json
          400:
            body:
              application/json:
                type: 400ResponseDataType
                example: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesexamples/1.0.0/examples/400Response-example.json
          404:
            body:
              application/json:
                type: 404ResponseDataType
                example: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesexamples/1.0.0/examples/404Response-example.json
          505:
            body:
              application/json:
                type: 500ResponseDataType
                example: !include /exchange_modules/872c6f8b-530b-4fac-8627-bc1c5081cdf2/httpstatuscodesexamples/1.0.0/examples/500Response-example.json
          
                  
      
                  
                
              
